codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: 0...100

  status:
    project:
      default:
        enabled: yes
        target: 0%
        threshold: 1%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    patch:	
      default:	
        enabled: no

comment: false
