matrix:
  include:
    - language: php
      php: 7.0
      before_script: composer require phpmd
      script:
        - php/lint.sh
        - php/test.sh

notifications:
  email:
    - mail@dcollins.info
