matrix:
  include:
    - language: php
      php: 7.0
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y phpmd
      script:
        - php/lint.sh
        - php/test.sh

notifications:
  email:
    - mail@dcollins.info
