matrix:
  include:
    - language: php
      php: 7.0
      before_script:
        - composer global require phpmd/phpmd
        - composer global require "squizlabs/php_codesniffer=*"
      script:
        - export PATH=~/.composer/vendor/bin:$PATH
        - php/lint.sh
        - php/test.sh
    - language: python
      - python: 3.5
      install:
        - pip install -r python/requirements/dev.txt
      script:
        - python/lint.sh

notifications:
  email:
    - mail@dcollins.info
